#!/bin/sh

#SWM name Quick Job
#SWM comment This is a simplest example of a job script
#SWM nodes 1
#SWM relocatable

#SWM account azure
#SWM flavor Standard_D4s_v3
#SWM cloud-image ubuntu-hpc/2204
#SWM containeroregistry swmregistry.azurecr.io
#SWM container-image jupyter/pytorch-notebook
#SWM container-image-tag cuda12-hub-5.2.1
#SWM storage swmblobcontainer

cat /etc/os-release
sleep 120
echo "Hello from simple job $SWM_JOBID"
