################################################################
# Runs a set of development windows/panes for Sky Port in tmux #
# To run it:                                                   #
#    tmuxinator start                                          #
################################################################

name: skyport
root: <%= ENV["SOURCES_PARENT_DIR"] %>/swm-core
pre_window: make cr
startup_window: core

windows:
  - core:
      layout: main-horizontal
      panes:
        - core:
          - scripts/run-in-shell.sh -x
  - core_logs:
      layout: main-horizontal
      panes:
        - core-logs:
          - tail -f /opt/swm/spool/node\@*/log/$(date +"%Y")
  - erlang_logs:
      layout: main-horizontal
      panes:
        - erlang-logs:
          - tail -f /opt/swm/spool/node\@*/log/erlang.log
  - sched_logs:
      layout: main-horizontal
      panes:
        - scheduler-logs:
          - tail -f /opt/swm/spool/node\@*/log/scheduler.log
  - terminal:
      layout: even-vertical
      panes:
        - list-jobs:
          - sleep 3
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-console-term
          - watch ./swm-console --job-list
        - list-nodes:
          - sleep 3
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-console-term
          - watch ./swm-console --node-list
  - gate:
      panes:
        - cloud-gate:
          - clear
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-cloud-gate
          - ./run.sh
  - jupyter:
      panes:
        - jupyterlab:
          - clear
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-jupyter-term
          - conda activate swm-jupyter
          - . .venv/bin/activate
          - jupyterhub
  - shell:
      root: <%= ENV["SOURCES_PARENT_DIR"] %>
      panes:
        - shell:
          - clear
