################################################################
# Runs a set of development windows/panes for Sky Port in tmux #
# To run it:                                                   #
#    tmuxinator start                                          #
################################################################

name: skyport
root: <%= ENV["SOURCES_PARENT_DIR"] %>/swm-core
pre_window: make cr
startup_window: core

windows:
  - core:
      layout: main-horizontal
      panes:
        - core:
          - scripts/run-in-shell.sh -x
  - logs:
      layout: main-horizontal
      panes:
        - core-logs:
          - tail -f /opt/swm/spool/node\@*/log/$(date +"%Y")
        - scheduler-logs:
          - tail -f /opt/swm/spool/node\@*/log/erlang.log
  - terminal:
      layout: 2b0d,137x56,0,0{26x56,0,0,2,110x56,27,0[110x27,27,0,7,110x28,27,28,8]}
      panes:
        - grid-tree:
          - sleep 3
          - watch ./scripts/swmctl grid tree
        - list-jobs:
          - sleep 3
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-console-term
          - watch ./swm-console --job-list
        - list-nodes:
          - sleep 3
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-console-term
          - watch ./swm-console --node-list
  - jupyter:
      panes:
        - jupyterlab:
          - clear
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-jupyter-term
          - conda activate swm-jupyter
          - . .venv/bin/activate
          - jupyterhub
  - gate:
      panes:
        - cloud-gate:
          - clear
          - cd <%= ENV["SOURCES_PARENT_DIR"] %>/swm-cloud-gate
          - ./run.sh
  - openstack:
      pre_window: make cr
      root: <%= ENV["SOURCES_PARENT_DIR"] %>/openstack-box
      panes:
        - vagrant:
          - clear
          - vagrant status 2>/dev/null | grep "Current machine states" -A 2
