#!/usr/bin/env bash

echo SWM_JOB_ID=${SWM_JOB_ID}
echo SWM_JOB_NAME=${SWM_JOB_NAME}
echo SWM_JOB_ACCOUNT=${SWM_JOB_ACCOUNT}
echo SWM_JOB_NODES=${SWM_JOB_NODES}
echo SWM_JOB_NODES_NUMBER=${SWM_JOB_NODES_NUMBER}
echo SWM_JOB_COMMENT=${SWM_JOB_COMMENT}
echo SWM_JOB_INPUT_FILES=${SWM_JOB_INPUT_FILES}
echo SWM_JOB_OUTPUT_FILES=${SWM_JOB_OUTPUT_FILES}
echo SWM_JOB_PORTS=${SWM_JOB_PORTS}
echo SWM_RELOCATABLE=${SWM_RELOCATABLE}
sleep 20
