openapi: 3.0.3
info:
  title: SkyPort core daemon user API
  description: |
    User facing API provided by swm-core daemon
  version: 1.0.0
  license:
    name: BSD 3-Clause License

paths:

  /user/node:
    get:
      summary: List all nodes
      description: >-
        Returns a list of node objects
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Node'

  /user/flavor:
    get:
      summary: List all flavors
      description: >-
        Returns a list of flavor objects
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flavor'

  /user/job:
    post:
      summary: Submit a new job
      description: 'A new job is submitted with a specific job script'
      responses:
        '200':
          description: successful operation of job submission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobToSubmit'
        '405':
          description: Invalid input

    get:
      summary: List all jobs
      description: >-
        Returns a list of job objects
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'

  '/user/job/{jobId}':
    get:
      summary: Find job by ID
      description: Returns a single job information
      parameters:
        - name: jobId
          in: path
          description: ID of job to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '400':
          description: Invalid job ID supplied
        '404':
          description: Job not found
      security:
        - api_key: []

    delete:
      summary: Cancels a job
      description: 'Cancels execution or pending of a job by job ID'
      parameters:
        - name: api_key
          in: header
          required: false
          schema:
            type: string
        - name: jobId
          in: path
          description: Job id to cancel
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '400':
          description: Invalid job ID

externalDocs:
  description: Find out more about SkyPort
  url: 'http://skyworkflows.com'

components:
  schemas:

    JobToSubmit:
      title: Job to submit
      description: A new job specification to submit
      type: object
      properties:
        name:
          type: string
          description: Job name
        script:
          type: string
          description: Content of job script
        nodes_number:
          type: integer
          format: int64
          description: Requested number of nodes

    Job:
      title: Job
      description: A job information that is known to SkyPort
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Job ID
        name:
          type: string
          description: Job name
        state:
          type: string
          description: Current job state
          enum:
            - R
            - Q
            - W
            - F
            - E
            - T
            - C
        submit_time:
          type: string
          description: Job submit time
        start_time:
          type: string
          description: Job start time
        end_time:
          type: string
          description: Job end time
        duration:
          type: integer
          format: int64
          minimum: 0
          description: Job run time
        exitcode:
          type: integer
          format: int64
          minimum: 0
          description: Job exit code
        signal:
          type: integer
          format: int64
          minimum: 0
          description: Signal if job is terminated
        node_names:
          type: array
          items:
            type: string
            format: hostname
          description: List of node names allocated for job
        remote_id:
          type: string
          format: uuid
          description: Remote site ID
        flavor_id:
          type: string
          format: uuid
          description: Node flavor ID
        comment:
          type: string
          description: Job comment string

    Flavor:
      title: Flavor
      description: A flavor information that is known to SkyPort
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Flavor ID
        name:
          type: string
          description: Flavor name
        remote_id:
          type: string
          description: Related remote object ID configured in swm-core
        cpus:
          type: integer
          format: int64
          description: CPU cores provided by the nodes of this flavor
        mem:
          type: integer
          format: int64
          minimum: 0
          description: Memory amount (in bytes) provided by the nodes of this flavor
        storage:
          type: integer
          format: int64
          minimum: 0
          description: Storage size (in bytes) provided by the nodes of this flavor
        price:
          type: number
          format: currency
          description: Price of a node of this flavor per hour

    Node:
      title: Node
      description: A node information
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Node ID
        name:
          type: string
          description: Node name in SkyPort
        host:
          type: string
          format: hostname
          description: Node system hostname
        api_port:
          type: integer
          format: int64
          minimum: 0
        state_power:
          type: string
          description: Node power state
          enum:
            - up
            - down
        state_alloc:
          type: string
          description: Node jobs allocation state
          enum:
            - idle
            - stopped
            - busy
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/NodeRole'

    Resource:
      title: Resource
      description: A resource information
      type: object
      properties:
        name:
          type: string
          description: Resource name
        count:
          type: integer
          format: int64
          minimum: 0

    NodeRole:
      title: Node role
      description: A node role information
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Role ID
        name:
          type: string
          description: Role name
        comment:
          type: string
          description: Role comment
