#!/bin/bash
#
# SPDX-FileCopyrightText: © 2021 Taras Shapovalov
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ME=$( readlink -f "$0" )
DIR=$( dirname "$ME" )
ROOT_DIR=$( dirname "$( dirname "$ME" )" )

## Export variables
source ${ROOT_DIR}/scripts/swm.env 1>/dev/null

if [ -e ${ROOT_DIR}/releases/start_erl.data ]; then
  START_ERL=`cat ${ROOT_DIR}/releases/start_erl.data`
  ERTS_VSN=${START_ERL% *}
  ESCRIPT=${ROOT_DIR}/erts-${ERTS_VSN}/bin/escript
else # run from sources
  ESCRIPT=escript
fi

SWMCTL=${DIR}/ctl.escript
MAX_HISTORY=1000
PROMPT_COLOR=Red
WRAPPER=rlwrap
USER_CONF_DIR=$HOME/.config/swm
COMPL_FILE=${USER_CONF_DIR}/ctl_completions
WRAPPER_ARGS="-p$PROMPT_COLOR --ansi-colour-aware -f $COMPL_FILE --always-readline --remember --histsize $MAX_HISTORY"

if [ ! -e ${USER_CONF_DIR} ]; then
  mkdir -p ${USER_CONF_DIR};
fi
touch $COMPL_FILE
command -v $WRAPPER >/dev/null || echo "$WRAPPER not found in $PATH"

if [ $# -eq "0" ]; then
  $WRAPPER $WRAPPER_ARGS $ESCRIPT $SWMCTL $@
else
  $ESCRIPT $SWMCTL $@
fi